# Generated by Django 4.2.5 on 2023-11-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrateur',
            old_name='idUtilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='apprenti',
            old_name='idMaitreAlternance',
            new_name='maitreAlternance',
        ),
        migrations.RenameField(
            model_name='apprenti',
            old_name='idTuteurPedagogique',
            new_name='tuteurPedagogique',
        ),
        migrations.RenameField(
            model_name='apprenti',
            old_name='idUtilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='coordinatricealternance',
            old_name='idUtilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='maitrealternance',
            old_name='idUtilisateur',
            new_name='utilisateur',
        ),
        migrations.RenameField(
            model_name='tuteurpedagogique',
            old_name='idUtilisateur',
            new_name='utilisateur',
        ),
    ]
