# Generated by Django 4.2.5 on 2023-11-08 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_utilisateur_datedenaissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='dateDeNaissance',
        ),
    ]
