# Generated by Django 4.2.5 on 2023-11-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_utilisateur_groups_utilisateur_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='motDePasse',
        ),
    ]
