# Generated by Django 4.2.5 on 2023-11-15 15:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_utilisateur_motdepasse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.TextField()),
                ('contenu', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createur_message', to=settings.AUTH_USER_MODEL)),
                ('destinataire', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('echeance', models.DateField(default=datetime.date.today)),
                ('chemin_fichier', models.CharField(max_length=255)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
