# Generated by Django 4.2.5 on 2023-11-23 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_apprenti_optionmajeure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 23, 10, 54, 48, 275112)),
        ),
    ]
