# Generated by Django 4.2.5 on 2023-11-23 13:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='apprenti',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.promotion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 23, 13, 47, 6, 556655)),
        ),
    ]
