# Generated by Django 4.2.5 on 2023-11-24 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_apprenti_promotion_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprenti',
            name='maitreAlternance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maitrealternance'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promotion'),
        ),
        migrations.AlterField(
            model_name='apprenti',
            name='tuteurPedagogique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tuteurpedagogique'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 11, 52, 28, 780691)),
        ),
    ]
