# Generated by Django 4.2.5 on 2023-11-24 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_apprenti_maitrealternance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raisonSociale', models.CharField(default='N/A', max_length=255)),
                ('adresse', models.CharField(default='N/A', max_length=255)),
                ('secteurDactivite', models.CharField(default='N/A', max_length=255)),
                ('description', models.TextField(default='N/A')),
                ('siret', models.CharField(default='N/A', max_length=255)),
                ('libelleCPNE', models.CharField(default='N/A', max_length=255)),
                ('codeIDCC', models.CharField(default='N/A', max_length=255)),
                ('conventionCollective', models.CharField(default='N/A', max_length=255)),
                ('codeNAF', models.CharField(default='N/A', max_length=255)),
                ('telephone', models.CharField(default='N/A', max_length=255)),
                ('email', models.CharField(default='N/A', max_length=255)),
                ('nombreSalarie', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GrilleEvaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Opco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raisonSociale', models.CharField(default='N/A', max_length=255)),
                ('adresse', models.CharField(default='N/A', max_length=255)),
                ('siret', models.CharField(default='N/A', max_length=255)),
                ('telephone', models.CharField(default='N/A', max_length=255)),
                ('email', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(default='N/A', max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='depot',
            old_name='chemin_fichier',
            new_name='cheminFichier',
        ),
        migrations.AddField(
            model_name='apprenti',
            name='classificationConventionCollective',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='descriptifPoste',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='dureeHebdoContrat',
            field=models.IntegerField(default=35),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='intitulePoste',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='maitrealternance',
            name='ancienEseo',
            field=models.BinaryField(default=False),
        ),
        migrations.AddField(
            model_name='maitrealternance',
            name='dernierDiplome',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='maitrealternance',
            name='fonction',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(default='0102030405', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 13, 59, 49, 550436)),
        ),
        migrations.AlterField(
            model_name='message',
            name='titre',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.CreateModel(
            name='ResponsableEntreprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fonction', models.CharField(max_length=255)),
                ('ancienEseo', models.BinaryField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(default='N/A', max_length=255)),
                ('dateDebut', models.DateField(default=datetime.date.today)),
                ('dateFin', models.DateField(default=datetime.date.today)),
                ('description', models.TextField(default='N/A')),
                ('apprenti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.apprenti')),
            ],
        ),
        migrations.CreateModel(
            name='EntretienSemestriel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.evenement')),
                ('maitreApprentissage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.maitrealternance')),
                ('tuteurPedagogique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tuteurpedagogique')),
            ],
        ),
        migrations.AddField(
            model_name='apprenti',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.entreprise'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='grilleEvaluation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grilleevaluation'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='opco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.opco'),
        ),
        migrations.AddField(
            model_name='maitrealternance',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.entreprise'),
        ),
    ]
