# Generated by Django 4.2.5 on 2023-11-24 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_tag_type_alter_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(to='api.tag'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 14, 49, 24, 347384)),
        ),
    ]
