# Generated by Django 4.2.5 on 2023-11-24 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_message_tags_alter_message_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entretiensemestriel',
            old_name='maitreApprentissage',
            new_name='maitreAlternance',
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 15, 30, 49, 543876)),
        ),
    ]
