# Generated by Django 4.2.5 on 2023-11-24 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_maitreapprentissage_entretiensemestriel_maitrealternance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 24, 15, 51, 53, 139358)),
        ),
    ]
