# Generated by Django 4.2.5 on 2023-12-13 09:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_depot_message_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(default='N/A')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 12, 13, 9, 32, 3, 170367)),
        ),
        migrations.CreateModel(
            name='CompetenceApprenti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commentaire', models.CharField(default='N/A', max_length=255)),
                ('semestre', models.CharField(choices=[('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('S9', 'S9'), ('S10', 'S10')], default='S5', max_length=3)),
                ('evaluation', models.CharField(choices=[('Non acquis', 'Non acquis'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquis', 'Acquis'), ('Non abordé en entreprise', 'Non abordé en entreprise')], default='Non acquis', max_length=24)),
                ('cible', models.CharField(choices=[('Non acquis', 'Non acquis'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquis', 'Acquis'), ('Non abordé en entreprise', 'Non abordé en entreprise')], default='Non acquis', max_length=24)),
                ('competence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.competence')),
                ('grilleEvaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grilleevaluation')),
            ],
        ),
    ]
