# Generated by Django 4.2.5 on 2024-01-11 14:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_competence_alter_message_time_competenceapprenti'),
    ]

    operations = [
        migrations.AddField(
            model_name='entretiensemestriel',
            name='noteSemestre',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 11, 14, 17, 39, 35225)),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenu', models.TextField(default='N/A')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(default=datetime.datetime(2024, 1, 11, 14, 17, 39, 39103))),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createur_commentaire', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.message')),
            ],
        ),
    ]
