# Generated by Django 4.2.5 on 2024-01-12 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_entretiensemestriel_notesemestre_alter_message_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='dateLivraison',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tag',
            name='couleur',
            field=models.CharField(default='000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 12, 8, 28, 17, 227550)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 12, 8, 28, 17, 222787)),
        ),
    ]
