# Generated by Django 4.2.5 on 2024-01-12 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_depot_datelivraison_tag_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 12, 13, 15, 58, 623779)),
        ),
        migrations.AlterField(
            model_name='depot',
            name='dateLivraison',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 12, 13, 15, 58, 619496)),
        ),
    ]
