# Generated by Django 4.2.5 on 2024-01-16 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_commentaire_time_alter_depot_datelivraison_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='visibilite',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 7, 54, 34, 602671)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 7, 54, 34, 599451)),
        ),
    ]
