# Generated by Django 4.2.5 on 2024-01-16 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_message_visibilite_alter_commentaire_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableentreprise',
            name='email',
        ),
        migrations.RemoveField(
            model_name='responsableentreprise',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='responsableentreprise',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='responsableentreprise',
            name='telephone',
        ),
        migrations.AddField(
            model_name='responsableentreprise',
            name='utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 8, 10, 5, 48842)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 8, 10, 5, 45633)),
        ),
    ]
