# Generated by Django 4.2.5 on 2024-01-16 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_responsableentreprise_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 18, 32, 5, 558547)),
        ),
        migrations.AlterField(
            model_name='entretiensemestriel',
            name='noteSemestre',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 16, 18, 32, 5, 555154)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='couleur',
            field=models.CharField(default='#000000', max_length=255),
        ),
    ]
