# Generated by Django 4.2.5 on 2024-01-17 09:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_commentaire_time_alter_message_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 17, 9, 58, 44, 172157)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 17, 9, 58, 44, 168916)),
        ),
        migrations.AlterField(
            model_name='role',
            name='libelle',
            field=models.CharField(choices=[('Apprenti', 'Apprenti'), ('TuteurPedagogique', 'TuteurPedagogique'), ('Administrateur', 'Administrateur'), ('CoordinatriceAlternance', 'CoordinatriceAlternance'), ('MaitreAlternance', 'MaitreAlternance'), ('ResponsableEntreprise', 'ResponsableEntreprise'), ('Professeur', 'Professeur'), ('MembreExterieur', 'MembreExterieur')], default='Apprenti', max_length=25),
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembreExterieur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
