# Generated by Django 4.2.5 on 2024-01-17 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_commentaire_time_alter_message_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 17, 9, 58, 56, 418902)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 17, 9, 58, 56, 414546)),
        ),
    ]
