# Generated by Django 4.2.5 on 2024-01-24 14:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_commentaire_time_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 24, 14, 34, 3, 353916)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 24, 14, 34, 3, 350774)),
        ),
        migrations.AlterField(
            model_name='role',
            name='libelle',
            field=models.CharField(choices=[('Apprenti', 'Apprenti'), ('TuteurPedagogique', 'TuteurPedagogique'), ('Administrateur', 'Administrateur'), ('CoordinatriceAlternance', 'CoordinatriceAlternance'), ('MaitreAlternance', 'MaitreAlternance'), ('ResponsableEntreprise', 'ResponsableEntreprise'), ('Professeur', 'Professeur'), ('MembreExterieur', 'MembreExterieur'), ('ResponsableFinance', 'ResponsableFinance'), ('ResponsableAdministration', 'ResponsableAdministration')], default='Apprenti', max_length=25),
        ),
        migrations.CreateModel(
            name='ResponsableFinance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ancienEseo', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsableAdministration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ancienEseo', models.BooleanField(default=False)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='apprenti',
            name='ResponsableAdministration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsableadministration'),
        ),
        migrations.AddField(
            model_name='apprenti',
            name='responsableFinance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.responsablefinance'),
        ),
    ]
