# Generated by Django 4.2.5 on 2024-01-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_commentaire_time_alter_message_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apprenti',
            old_name='responsableFinance',
            new_name='ResponsableFinance',
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 24, 14, 34, 55, 817123)),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 1, 24, 14, 34, 55, 813940)),
        ),
    ]
